name: Comment on Pull Request
on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Thank you for your contribution! We hope to see you soon!'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
